# Generated by Django 5.0.14 on 2026-01-07 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('EUR', '€ Euro'), ('USD', '$ Dollar'), ('GBP', '£ Livre'), ('XOF', 'CFA Franc')], default='EUR', max_length=3, verbose_name='Devise')),
                ('monthly_income_goal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Objectif de revenu mensuel')),
                ('monthly_savings_goal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name="Objectif d'épargne mensuel")),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Photo de profil')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil utilisateur',
                'verbose_name_plural': 'Profils utilisateurs',
            },
        ),
    ]
